import { NavStore, AppPage, CurrentPopup, LoginPageStore } from "store.slint";
import { VerticalBox } from "std-widgets.slint";
import { LoginPage } from "pages/login-page.slint";
import { LoadingPopup } from "popups/loading-popup.slint";
import { MessageBoxPopup } from "popups/messagebox-popup.slint";

export component Main inherits Window {
    title: "Mattermost - GUI";

    preferred-width: 800px;
    preferred-height: 600px;

    if NavStore.currentPage == AppPage.LoginPage: LoginPage {
        data <=> LoginPageStore.data;

        callback-login-clicked => {
            LoginPageStore.login-clicked();
        }
        
        callback-forgot-password-clicked => {
          LoginPageStore.forgot-password-clicked();
        }
    }

    if NavStore.currentPopup == CurrentPopup.Loading: Rectangle {
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        
        LoadingPopup {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
        }
    }

    if NavStore.currentPopup == CurrentPopup.MessageBox: Rectangle {
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        
        MessageBoxPopup {
            data: NavStore.messageBoxData;
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            
        }
    }

}

export { LoginPageStore, NavStore }