export enum AppPage {
  LoginPage,
  ChatPage,
  SettingsPage,
}

export enum CurrentPopup {
  None,
  Loading,
  MessageBox,
}

export struct LoginPageData {
  username: string,
  password: string,
  remember_me: bool,
  server_url: string,
}

export struct MessageBoxData {
  title: string,
  message: string,
  is_error: bool,
}

export global LoginPageStore {
    in-out property <LoginPageData> data;

    callback login-clicked();
    callback forgot-password-clicked();
}

export global NavStore {
  in property <AppPage> currentPage: AppPage.LoginPage;
  in-out property <CurrentPopup> currentPopup: CurrentPopup.None;
  
  in-out property <MessageBoxData> messageBoxData;
} 
