export enum AppPage {
  LoginPage,
  ChatPage,
  SettingsPage,
}

export enum CurrentPopup {
  None,
  Loading,
  MessageBox,
}

export struct LoginPageStore {
  username: string,
  password: string,
  remember_me: bool,
  server_url: string,
}

export struct MessageBoxData {
  title: string,
  message: string,
  is_error: bool,
}

export global Store {
  in property <AppPage> currentPage: AppPage.LoginPage;
  in-out property <CurrentPopup> currentPopup: CurrentPopup.None;
  
  in-out property <LoginPageStore> loginPage;
  in-out property <MessageBoxData> messageBoxData;
}
